name: ams_android
description: "Frontend for ams android app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependency Injection
  injectable: ^2.7.1+4
  get_it: ^9.2.0
  # Routing
  auto_route: ^11.1.0
  # State Management
  flutter_bloc: ^9.1.1
  # sqlite database
  sqflite: ^2.4.2
  path: ^1.9.1
  # Networking
  retrofit: ^4.9.2
  dio: ^5.9.1
  pretty_dio_logger: ^1.4.0
  #Permision Handler Utility
  permission_handler: ^12.0.1
  # Location
  geolocator: ^14.0.2

  cupertino_icons: ^1.0.8
  intl_utils: ^2.8.7
  sign_in_button: ^3.0.0
  font_awesome_flutter: ^10.7.0
  equatable: ^2.0.5

  json_annotation: ^4.10.0

dev_dependencies:
  build_runner: ^2.10.5
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Dongle
      fonts:
        - asset: assets/fonts/Dongle-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dongle-Regular.ttf
          weight: 500
        - asset: assets/fonts/Dongle-Light.ttf
          weight: 300
    - family: AfacadFlux
      fonts:
        - asset: assets/fonts/AfacadFlux-Regular.ttf
          weight: 400
        - asset: assets/fonts/AfacadFlux-Thin.ttf
          weight: 100
        - asset: assets/fonts/AfacadFlux-Light.ttf
          weight: 300
        - asset: assets/fonts/AfacadFlux-Medium.ttf
          weight: 500
        - asset: assets/fonts/AfacadFlux-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AfacadFlux-Bold.ttf
          weight: 700
        - asset: assets/fonts/AfacadFlux-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/AfacadFlux-Black.ttf
          weight: 900
        - asset: assets/fonts/AfacadFlux-ExtraBold.ttf
          weight: 800